export const CHAT_FOLLOWUP_MESSAGE_MAX_LENGTH = 2000;

export const CHAT_FOLLOWUP_OUTPUT_TOKEN_LIMIT = 8192;

export const CHAT_FOLLOWUP_STEP_LIMIT = 6;

export const CHAT_TURN_LEASE_DURATION_MS = 5 * 60 * 1000;

export const CHAT_ARCHIVE_PAGE_SIZE = 20;

export const CHAT_STANDALONE_PROMPT_MAX_LENGTH = 500;

export const CHAT_STANDALONE_MARKDOWN_MAX_LENGTH = 50_000;

export const CHAT_TITLE_MAX_LENGTH = 80;
