export const THREAD_FOLLOWUP_MESSAGE_MAX_LENGTH = 2000;

export const THREAD_FOLLOWUP_OUTPUT_TOKEN_LIMIT = 8192;

export const THREAD_FOLLOWUP_STEP_LIMIT = 6;

export const THREAD_TURN_LEASE_DURATION_MS = 5 * 60 * 1000;

export const THREAD_LIST_MAX_ITEMS = 100;

export const THREAD_STANDALONE_PROMPT_MAX_LENGTH = 500;

export const THREAD_STANDALONE_MARKDOWN_MAX_LENGTH = 50_000;

export const THREAD_TITLE_MAX_LENGTH = 80;
